name: kvantum
base: core22
adopt-info: version
summary: Theme Snap with Kvantum
description: |
  This is an attempt to bring kvantum theming in Snaps, still in early stage.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

package-repositories:
 - type: apt
   ppa: papirus/papirus


slots:
  kvantum-manager:
    interface: dbus
    bus: session
    name: com.github.tsujan.kvantum
  kvantum:
    interface: content
    source:
      read:
        - $SNAP/usr/share/Kvantum/*
        - $SNAP/usr/share/themes/*
        
apps:
  kvantum:
    command: usr/bin/kvantummanager
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.tsujan.kvantum
    desktop: usr/share/applications/kvantummanager.desktop

parts:
  kvantum:
    plugin: nil
    stage-packages:
      - qt5-style-kvantum 
      - adapta-kde 
      - arc-kde
