name: kvantum
base: core22
adopt-info: kvantum
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
slots:
  kvantum-manager:
    interface: dbus
    bus: session
    name: com.github.tsujan.kvantum

apps:
  kvantum:
    command: usr/bin/kvantummanager
    extensions:
      - kde-neon
    plugs:
      - home
      - raw-usb
      - network
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.tsujan.kvantum
    desktop: usr/share/applications/kvantummanager.desktop
    
parts:
  kvantum:
    source: https://github.com/tsujan/Kvantum.git
    source-tag: V1.0.10
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-snaps:
      - kf5-5-105-qt-5-15-9-core22-sdk
    build-packages:
      - build-essential
      - libx11-dev
      - qtbase5-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      cd Kvantum
      mkdir build && cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr
      make
      make install
      
      
